hm_lesson_3
Tippman/geekshop pull request #2
Opened 2020-12-07 22:31 UTC by Tippman

2020-12-08 07:53 UTC, Vokler requested changes

2020-12-08 07:53 UTC, Vokler commented on .gitignore
> +media
Добавьте сюда еще `__pycache__`, предварительно удалив из проекта (показывал, как это сделать на 3ем уроке)

2020-12-08 07:53 UTC, Vokler commented on mainapp/admin.py
> +from .models import Category, Product
Рекомендую использовать (вернее не я, а pep8) абсолютный импорт, то есть from mainapp.services
https://www.python.org/dev/peps/pep-0008/#id23

2020-12-08 07:53 UTC, Vokler commented on mainapp/formats/en/formats.py
> +THOUSAND_SEPARATOR = ' '
А что это за файл? Думаю тоже служебный и желательно занести в .gitignore

2020-12-08 07:53 UTC, Vokler commented on mainapp/models.py
> +        verbose_name = 'Категория'
класс Meta лучше хранить над всеми методами, то есть до get_absolute_url и __str__ (просто как совет)

2020-12-08 07:53 UTC, Vokler commented on mainapp/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Вы проверяли, работает загрузка изображения?
Просто в settings вы указали, что изображение будет сохраняться в папку media, а тут вы пишите, что в mainapp.

2020-12-08 07:53 UTC, Vokler commented on mainapp/views.py
> +from .models import Category, Product
Тут та же история с абсолютными импортами

2020-12-08 07:53 UTC, Vokler commented on mainapp/views.py
> +    pass
Если вы добавили в urls.py возможность переходить в категорию по id, то когда вы реализуете эту ф-цию, она выкинет ошибки, так как нужен параметр, отвечающий за pk.
Прочитайте методичку от 3его урока (к концу методички) или я на 4 занятии этот момент расскажу

2020-12-08 07:53 UTC, Vokler commented on requirements.txt
> +sqlparse==0.4.1
pytz и sqlparse не нужно добавлять так как они установяться автоматически при установки Django

2020-12-08 15:47 UTC, Tippman commented on .gitignore
> +media
удалил скрытые файлы, добавил `__pycache__` в gitignore, сделал навый коммит и запушил, но эти папки не удалились из репозитория, другие удаленные папки удалились

2020-12-08 15:48 UTC, Tippman commented on mainapp/admin.py
> +from .models import Category, Product
исправил

2020-12-08 15:50 UTC, Tippman commented on mainapp/formats/en/formats.py
> +THOUSAND_SEPARATOR = ' '
это файл для настроек локализации, чтобы числа разделялись пробелом по тысячам и выводилась запятая вместо точки. Данную папку удалил и добавил игнор

2020-12-08 15:53 UTC, Tippman commented on mainapp/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
загрузка изображений работает, т.к. в шаблоне указал `src="{{ item.image.url }}"` т.е. берем полный урл до картинки. У меня в папке media создана папка mainapp для разделения картинок по приложениям, есть смысл вообще в таком разделении?

2020-12-08 15:54 UTC, Tippman commented on mainapp/views.py
> +from .models import Category, Product
исправил

2020-12-08 15:55 UTC, Tippman commented on mainapp/views.py
> +    pass
да, я понимаю, когда буду писать эту функцию передам в нее аргументом еще и pk

2020-12-08 15:56 UTC, Tippman commented on requirements.txt
> +sqlparse==0.4.1
удалил эти строки, они создаются автоматом при выполнении команды freeze

2020-12-08 16:11 UTC, Tippman commented on .gitignore
> +media
разобрался, пришлось сделать еще пару коммитов))

2020-12-09 10:45 UTC, Vokler commented on mainapp/admin.py
> +from .models import Category, Product
Чтобы запускать питоновские скрипты в проекте с джанго, нужно воспользоваться shell
То есть вот
https://stackoverflow.com/questions/16853649/how-to-execute-a-python-script-from-the-django-shell

2020-12-09 10:48 UTC, Vokler commented on mainapp/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Да, хорошее решение. Оставляйте так как есть у вас 👍

2020-12-09 10:49 UTC, Vokler approved these changes

2020-12-09 10:50 UTC, merged