lesson_4
Tippman/geekshop pull request #3
Opened 2020-12-09 23:12 UTC by Tippman

2020-12-09 23:15 UTC, Tippman commented
Проблема

2020-12-10 16:44 UTC, Vokler requested changes

2020-12-10 16:44 UTC, Vokler commented on authapp/forms.py
> +        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'age', 'avatar')
Поля age и avatar - лишние, так как мы их не добавляем при создании аккаунта.
Или вы решили добавить? Если да, то ок. Но в register.html я их не увидел

2020-12-11 11:17 UTC, Tippman commented on authapp/forms.py
> +        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'age', 'avatar')
Удалил из fields формы поля age и avatar, думал раз они есть в модели нужно и форму добавить... в модели по ДЗ оставил эти поля.

2020-12-12 11:53 UTC, Vokler approved these changes

2020-12-12 11:53 UTC, merged